### ISSUE TITLE
Unexpected keyword argument 'ks' in RankBasedEvaluator

### ISSUE THREAD

**Issue by psitsme26** [migalkin/ilpc2022#4]
code doesn't run, in requirement.txt pykeen version mentioned 1.8 or above but pykeen latest version available is 1.7

Is there a plan to release pykeen 1.8 version ?

**Comment by migalkin** [comment]
Yes, pykeen 1.8 will be released in a few days. Meanwhile, please install the latest version from the master branch with 
```
pip install git+https://github.com/pykeen/pykeen.git
```

**Comment by psitsme26** [comment]
Installed pykeen using pip install git+https://github.com/pykeen/pykeen.git, but facing error "TypeError: __init__() got an unexpected keyword argument 'ks'", Please see the error stack trace below:

```python-traceback
Traceback (most recent call last):
  File "main.py", line 226, in <module>
    main()
  File "E:\pykeen\ilpc2022-main\venv\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "E:\pykeen\ilpc2022-main\venv\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "E:\pykeen\ilpc2022-main\venv\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\pykeen\ilpc2022-main\venv\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "main.py", line 173, in main
    valid_evaluator = RankBasedEvaluator(mode=VALIDATION, ks=(1, 3, 5, 10, 100))
  File "E:\pykeen\ilpc2022-main\venv\lib\site-packages\pykeen\evaluation\rank_based_evaluator.py", line 228, in __init__
    super().__init__(
TypeError: __init__() got an unexpected keyword argument 'ks'
```

**Comment by psitsme26** [comment]
I think I fixed it after removing ks as argument from line 173 and 174 in main.py
    valid_evaluator = RankBasedEvaluator(mode=VALIDATION)
    test_evaluator = RankBasedEvaluator(mode=TESTING)

The code is running now. I think this is right @migalkin

**Comment by mberr** [comment]
related: https://github.com/pykeen/pykeen/pull/827

**Comment by migalkin** [comment]
The PR for PyKEEN has been merged and I updated the main script with correct evaluators instantiation in 3d0166dc78a91c6f9075e988f7ddaa68b10f3704- it works with the master pykeen branch now. @psitsme26 could you please confirm?
